# conda env create -f environment.yml
name: sliderule
channels:
  - conda-forge
dependencies:
  - cartopy
  - geopandas
  - h5py
  - ipykernel
  - ipywidgets>=7.6,<8.0
  - ipyleaflet>=0.15
  - jupyterlab=3
  - jupyterlab_widgets
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyproj
  - pytables
  - python=3.8
  - requests
  - scipy
  - setuptools_scm
  - shapely
  - tk
  - xyzservices
  - pip:
      - -e ./
