# conda env create -f environment.yml
name: sliderule
channels:
  - conda-forge
dependencies:
  - python=3.8
  - setuptools_scm
  - cartopy
  - ipykernel
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyproj
  - scipy
  - shapely
  - requests
  - pip:
      - -e ./
