# conda env create -f environment.yml
name: sliderule
channels:
  - conda-forge
dependencies:
  - cartopy
  - geopandas
  - h5py
  - ipykernel
  - ipywidgets
  - ipyleaflet
  - jupyterlab>=3
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyproj
  - python=3.8
  - requests
  - scipy
  - setuptools_scm
  - shapely
  - tk
  - pip:
      - -e ./
